# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
smtp_hostname: 'smtp.mailgun.org'
mailgun_username: 'postmaster@sandbox43f2b68aecbe429b90c9a5f3c61c21af.mailgun.org'
mailgun_password: '023a5914869c2916614916fd19949b78-4879ff27-2f438c75'
mailgun_domain: 'sandbox43f2b68aecbe429b90c9a5f3c61c21af.mailgun.org'

AWS_ACCESS_KEY_ID: "AKIA6QGMY2EE3X6CWX6Q"
AWS_SECRET_ACCESS_KEY: "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"
S3_BUCKET_NAME: "haltbucket-dev"
AWS_REGION: "us-east-2"
